% fprintf("bat_ApEn\n");
% bat_ApEn;
% fprintf("bat_c0complex\n");
% bat_c0complex;
% fprintf("bat_kolmgolov_entropy\n");
% bat_kolmgolov_entropy;
% fprintf("bat_LE\n");
% bat_LE;
% fprintf("bat_LZC\n");
% bat_LZC;
% fprintf("bat_Permutation_entropy\n");
% bat_Permutation_entropy;
% fprintf("bat_RC\n");
% bat_RC;
% fprintf("bat_singular_entropy\n");
% bat_singular_entropy;
% fprintf("bat_spectral_entropy\n");
% bat_spectral_entropy;

fprintf("bat_c0complex\n");
bat_c0complex;
fprintf("bat_singular_entropy\n");
bat_singular_entropy;
fprintf("bat_spectral_entropy\n");
bat_spectral_entropy;
fprintf("bat_LE\n");
bat_LE;
fprintf("bat_Permutation_entropy\n");
bat_Permutation_entropy;
fprintf("bat_kolmgolov_entropy\n");
bat_kolmgolov_entropy;
